name: Publish to PyPI  # ワークフローの名前（GitHub上で表示される）

on:
  push:
    tags:
      - "v*"           # タグ名が "v" で始まる push（例: v0.1.0）をトリガーにする

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # GitHubのUbuntuランナーを使用
    steps:
      - uses: actions/checkout@v3
        # リポジトリをチェックアウトしてGitHub ActionsのVMにコードを取り込む

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        # Pythonのバージョンを指定（3.8〜3.12などに変更可能）

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip build
      #   # `build` パッケージは `pyproject.toml` or `setup.py` を元にパッケージを作成する

      # - name: Build package
      #   run: python -m build
      #   # sdist（.tar.gz）と wheel（.whl）を dist/ に作成

      - name: Install Hatch
        run: pip install hatch hatch-vcs
        # hatch build は `pyproject.toml` を元にパッケージを作成する

      - name: Build with Hatch
        run: hatch build
        # sdist（.tar.gz）と wheel（.whl）を dist/ に作成

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}